GET http://localhost:8080/api/me HTTP/1.1
content-type: application/json

# POST http://localhost:8080/api/login HTTP/1.1
# content-type: application/json

# {
#   "username": "RealGirl007",
#   "password": "RealGirl007"
# }